### PR TITLE
updated InstallAssistant.pkg

### PR DESCRIPTION
**Pull request by kirillrdy**
first link from https://mrmacintosh.com/macos-ventura-13-full-installer-database-download-directly-from-apple/

@MatthewCroughan what do you think about nixfmt-rfc-style ?

### CODE REVIEW

**Comment by MatthewCroughan** [comment]
@kirillrdy I don't really care about automated formatting, but if you prefer a certain kind of formatting when you make the PR, just make it a separate commit and I'll accept it.

How do you think they get the latest URL? I want to automate this.

**Comment by kirillrdy** [comment]
i'll ignore auto-formatting for now.

re URLs, if you have uptodate macos ? https://gist.github.com/b0gdanw/26f528dda5abea7ce6fe633ca2ef1063

**Comment by MatthewCroughan** [comment]
Just to be clear, by automated formatting, I mean enforcement at a CI/commit-hook level.

**Comment by MatthewCroughan** [comment]
Maybe some of these InstallAssistant packages are available on archive.org as a backup, or may eventually be. We could use those if they are.

**Comment by kirillrdy** [comment]
> Maybe some of these InstallAssistant packages are available on archive.org as a backup, or may eventually be. We could use those if they are.

an other ( more painful alternative ) is to boot into RecoveryImage and download latest installer using their GUI :-)

**Comment by MatthewCroughan** [comment]
The CI machine is having hardware issues, and I'm not at home to fix it. So I'm having a bit of trouble verifying this the way I'd like to. Is it possible you could verify it and tell me if it works as expected up to 5 times with `nix build --rebuild` ? @kirillrdy

**Comment by kirillrdy** [comment]
> The CI machine is having hardware issues, and I'm not at home to fix it. So I'm having a bit of trouble verifying this the way I'd like to. Is it possible you could verify it and tell me if it works as expected up to 5 times with `nix build --rebuild` ? @kirillrdy

I've built this at least twice on two different machines, but will do more and will report

**Comment by kirillrdy** [comment]
ok i've done 5 rebuilds

```
[kirillvr@tsutenkaku:~/NixThePlanet]$ nix build .#macos-ventura-image --rebuild
error: derivation '/nix/store/cy0cmdbkw3zdki5ksdlrjx8jfl3hk61i-mac_hdd_ng.qcow2.drv' may not be deterministic: output '/nix/store/0z2pwrvpxi3j8gvscfdnmmkbi59bxdf4-mac_hdd_ng.qcow2' differs
```

I assume old image was also non deterministic.

no urgency to merge this, take your time

**Comment by MatthewCroughan** [comment]
Yeah derivations aren't deterministic, and don't need to be. One of Nix's strengths is allowing you to model multiple kinds of reproducible models, and cache non-deterministic behavior, whilst also having the option of using content-addressed models as well. In this case all that matter is whether the derivations succeed and produce $out or not, and if that worked for you then I'm happy to merge it here.

**Pull request merged**
