### PR TITLE
Update MacOS ventura to 13.7

### LINKED ISSUE #34: 403 when trying to download image
Getting

 error: unable to download 'https://swcdn.apple.com/content/downloads/46/31/052-96247-A_MLN9N00Y8W/dmml3up52hrsb01krjtczmdhexiruv1b5m/InstallAssistant.pkg': HTTP error 403
 
 Has anyone else seen this?

### PR DESCRIPTION
**Pull request by aciceri**
Fixes #34

### CODE REVIEW

**Comment by aciceri** [comment]
@MatthewCroughan It looks like the build was stopped, ti says `FatalError {fatalErrorMessage = "user interrupt"} (worker: ExitFailure 1)`. Did you manually stop it?

**Comment by MatthewCroughan** [comment]
@aciceri the CI machine is having a bad day, I have been kicking it a bunch. Have never been able to debug whether it's the disk or the memory, or even the CPU.

**Comment by MatthewCroughan** [comment]
Yeah, the CI machine is experiencing hardware failure, but I know it works so I'll just merge it for now, and later on I'll fix the CI box.

**Comment by MatthewCroughan** [comment]
@aciceri Actually, it looks like they updated the product version string from 13.6 to 13.7 in this release, which the VM test caught, so I'm updating that now.

**Comment by aciceri** [comment]
You mean the repeatibility test? I cannot find where it looks for the product version.
Anyway glad you figured it out!

**Comment by MatthewCroughan** [comment]
@aciceri It's defined here

https://github.com/MatthewCroughan/NixThePlanet/blob/2f622af217807da78e44a5a15f620743dac57f46/makeDarwinImage/vm-test.nix#L22-L41

**Pull request merged**
